/**
 * Supabase Database TypeScript Types
 *
 * This file will be auto-generated by Supabase CLI after migrations run:
 *   supabase gen types typescript --project-id <project-id> > types/database.types.ts
 *
 * For now this is a placeholder that allows the TypeScript build to succeed.
 * Replace with generated types after running the database migrations in Sprint 2.
 *
 * See Database Schema Specification §17 for expected types.
 */

// ─── Enum types (from Database Schema §5) ──────────────────────────────────

export type UserRole = "customer" | "staff" | "admin";
export type ProductCategoryType = "phone" | "tablet" | "laptop" | "accessory" | "other";
export type DeviceCondition = "like_new" | "excellent" | "good" | "fair";
export type ProductStatus = "draft" | "active" | "archived" | "sold_out";
export type IntakeStatus =
  | "received"
  | "testing"
  | "needs_imei_check"
  | "needs_photos"
  | "hold_period"
  | "ready_to_list"
  | "converted_to_product"
  | "rejected";
export type VerificationStatus = "not_checked" | "passed" | "failed" | "needs_review";
export type TestingStatus = "not_started" | "in_progress" | "passed" | "failed" | "needs_review";
export type CarrierType =
  | "unlocked"
  | "att"
  | "verizon"
  | "tmobile"
  | "sprint"
  | "other"
  | "unknown";
export type OrderStatus =
  | "pending"
  | "paid"
  | "processing"
  | "ready_for_pickup"
  | "shipped"
  | "delivered"
  | "picked_up"
  | "cancelled"
  | "refunded";
export type FulfillmentMethod = "pickup" | "shipping";
export type PaymentStatus = "unpaid" | "paid" | "failed" | "refunded" | "partially_refunded";
export type WarrantyClaimStatus =
  | "none"
  | "submitted"
  | "under_review"
  | "approved"
  | "denied"
  | "resolved";
export type RequestStatus =
  | "submitted"
  | "under_review"
  | "approved"
  | "denied"
  | "completed"
  | "cancelled";
export type CouponType = "percentage" | "fixed_amount" | "free_shipping";
export type SellerIdType =
  | "drivers_license"
  | "state_id"
  | "passport"
  | "military_id"
  | "other";
export type AcquisitionPaymentMethod =
  | "cash"
  | "check"
  | "zelle"
  | "venmo"
  | "store_credit"
  | "other";
export type AuditAction =
  | "create"
  | "update"
  | "delete"
  | "status_change"
  | "role_change"
  | "login"
  | "export"
  | "request_submitted";

/**
 * Supported locales at the application layer.
 * Not enforced by DB CHECK constraints — validated application-side only.
 * See Database Schema Specification §6.1 and §10 notes.
 */
export type SupportedLocale = "en" | "es";

// ─── Placeholder Database type (replaced by supabase gen types) ────────────

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          role: UserRole;
          avatar_url: string | null;
          preferred_locale: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          phone?: string | null;
          role?: UserRole;
          avatar_url?: string | null;
          preferred_locale?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          phone?: string | null;
          role?: UserRole;
          avatar_url?: string | null;
          preferred_locale?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          type: ProductCategoryType;
          description: string | null;
          translations: Json;
          image_url: string | null;
          sort_order: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          type: ProductCategoryType;
          description?: string | null;
          translations?: Json;
          image_url?: string | null;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["categories"]["Insert"]>;
      };
      products: {
        Row: {
          id: string;
          category_id: string | null;
          slug: string;
          title: string;
          subtitle: string | null;
          description: string | null;
          translations: Json;
          category_type: ProductCategoryType;
          brand: string | null;
          model: string | null;
          storage: string | null;
          color: string | null;
          carrier: CarrierType | null;
          original_carrier: CarrierType | null;
          condition: DeviceCondition | null;
          battery_health: number | null;
          battery_cycle_count: number | null;
          supported_bands: string[] | null;
          network_compatibility: string[] | null;
          // Private fields — never expose publicly
          imei: string | null;
          serial_number: string | null;
          cost: number | null;
          acquisition_source: string | null;
          acquisition_date: string | null;
          internal_device_notes: string | null;
          // /end private fields
          is_clean_imei: boolean | null;
          imei_verification_status: VerificationStatus;
          imei_verified_at: string | null;
          imei_verified_by: string | null;
          is_unlocked: boolean | null;
          activation_lock_removed: boolean;
          is_tested: boolean;
          testing_status: TestingStatus;
          tested_at: string | null;
          tested_by: string | null;
          testing_notes: string | null;
          is_data_wiped: boolean;
          factory_reset_verified: boolean;
          includes_charger: boolean;
          includes_cable: boolean;
          warranty_days: number;
          price: number;
          compare_at_price: number | null;
          quantity: number;
          sku: string | null;
          barcode: string | null;
          status: ProductStatus;
          featured: boolean;
          allow_pickup: boolean;
          allow_shipping: boolean;
          seo_title: string | null;
          seo_description: string | null;
          seo_translations: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["products"]["Row"]> & {
          slug: string;
          title: string;
          category_type: ProductCategoryType;
          price: number;
          quantity: number;
        };
        Update: Partial<Database["public"]["Tables"]["products"]["Row"]>;
      };
      settings: {
        Row: {
          key: string;
          value: Json;
          description: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          description?: string | null;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["settings"]["Insert"]>;
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          user_id: string | null;
          customer_email: string;
          customer_name: string | null;
          customer_phone: string | null;
          customer_locale: string;
          guest_access_token: string;
          status: OrderStatus;
          payment_status: PaymentStatus;
          fulfillment_method: FulfillmentMethod;
          subtotal: number;
          discount_total: number;
          shipping_total: number;
          tax_total: number;
          total: number;
          currency: string;
          shipping_insurance_amount: number;
          shipping_address_id: string | null;
          billing_address_id: string | null;
          tracking_number: string | null;
          shipping_carrier: string | null;
          shipped_at: string | null;
          pickup_location_name: string | null;
          pickup_location_address: string | null;
          stripe_checkout_session_id: string | null;
          stripe_payment_intent_id: string | null;
          stripe_tax_calculation_id: string | null;
          tax_jurisdiction: string | null;
          coupon_id: string | null;
          coupon_code: string | null;
          notes: string | null;
          admin_notes: string | null;
          paid_at: string | null;
          fulfilled_at: string | null;
          cancelled_at: string | null;
          refunded_at: string | null;
          warranty_started_at: string | null;
          cancellation_requested_at: string | null;
          cancellation_request_reason: string | null;
          cancellation_request_status: RequestStatus | null;
          cancellation_reviewed_by: string | null;
          cancellation_reviewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["orders"]["Row"]> & {
          order_number: string;
          customer_email: string;
          customer_locale: string;
          fulfillment_method: FulfillmentMethod;
        };
        Update: Partial<Database["public"]["Tables"]["orders"]["Row"]>;
      };
      coupons: {
        Row: {
          id: string;
          code: string;
          type: CouponType;
          value: number;
          active: boolean;
          usage_limit: number | null;
          used_count: number;
          minimum_order_amount: number | null;
          starts_at: string | null;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["coupons"]["Row"]> & {
          code: string;
          type: CouponType;
          value: number;
        };
        Update: Partial<Database["public"]["Tables"]["coupons"]["Row"]>;
      };
      webhook_events: {
        Row: {
          id: string;
          stripe_event_id: string;
          event_type: string;
          processed_at: string;
          payload: Json | null;
          error: string | null;
        };
        Insert: {
          stripe_event_id: string;
          event_type: string;
          payload?: Json | null;
          error?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["webhook_events"]["Row"]>;
      };
    };
    Views: {
      public_products: {
        Row: Omit<
          Database["public"]["Tables"]["products"]["Row"],
          | "imei"
          | "serial_number"
          | "cost"
          | "acquisition_source"
          | "acquisition_date"
          | "internal_device_notes"
          | "imei_verified_by"
          | "tested_by"
        >;
      };
      customer_order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string | null;
          product_title: string;
          product_slug: string | null;
          product_sku: string | null;
          product_image_url: string | null;
          unit_price: number;
          quantity: number;
          line_total: number;
          device_brand: string | null;
          device_model: string | null;
          device_storage: string | null;
          device_color: string | null;
          device_condition: DeviceCondition | null;
          battery_health: number | null;
          warranty_days: number;
          warranty_expires_at: string | null;
          created_at: string;
          // NOTE: product_imei and product_serial_number intentionally excluded
        };
      };
    };
    Functions: Record<string, never>;
    Enums: {
      user_role: UserRole;
      product_category_type: ProductCategoryType;
      device_condition: DeviceCondition;
      product_status: ProductStatus;
      intake_status: IntakeStatus;
      verification_status: VerificationStatus;
      testing_status: TestingStatus;
      carrier_type: CarrierType;
      order_status: OrderStatus;
      fulfillment_method: FulfillmentMethod;
      payment_status: PaymentStatus;
      warranty_claim_status: WarrantyClaimStatus;
      request_status: RequestStatus;
      coupon_type: CouponType;
      seller_id_type: SellerIdType;
      acquisition_payment_method: AcquisitionPaymentMethod;
      audit_action: AuditAction;
    };
  };
}
