"use server";

/**
 * Checkout Server Actions
 *
 * createCheckoutSession — validates cart, creates pending order, creates Stripe
 * Checkout Session, returns the Stripe redirect URL.
 *
 * Security rules (per API Spec §10):
 *  - Never trust client-provided prices — re-fetch from DB
 *  - Never decrement inventory here — only after Stripe webhook
 *  - Rate-limit: 10 checkout attempts / 5 min / IP
 *  - Validate fulfillment method per product
 *  - guest_access_token auto-generated by DB (gen_random_uuid())
 *  - Stripe collects shipping address for tax (shipping_address_collection)
 */

import { z } from "zod";
import { headers } from "next/headers";
import Stripe from "stripe";
import { stripe } from "@/lib/stripe/client";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { getCart } from "@/lib/cart/cart-queries";
import { isCheckoutAllowed } from "@/lib/rate-limit";
import { getStoreSettings, isStripeTaxEnabled } from "@/lib/data/settings";
import type { CartItemWithProduct } from "@/lib/cart/cart-queries";
import type { Database } from "@/types/database.types";

type FulfillmentMethod = Database["public"]["Enums"]["fulfillment_method"];

// ─── Input schema ─────────────────────────────────────────────────────────────

const checkoutSchema = z.object({
  customerEmail: z.string().email("Enter a valid email address"),
  customerName: z.string().min(2, "Full name is required"),
  customerPhone: z.string().optional(),
  fulfillmentMethod: z.enum(["pickup", "shipping"]),
  couponCode: z.string().optional(),
  customerLocale: z.string().optional(),
});

export type CheckoutInput = z.infer<typeof checkoutSchema>;

export interface CheckoutResult {
  error?: string;
  url?: string;
}

// ─── Main action ──────────────────────────────────────────────────────────────

export async function createCheckoutSession(
  rawInput: CheckoutInput,
): Promise<CheckoutResult> {
  // 1. Validate input
  const parsed = checkoutSchema.safeParse(rawInput);
  if (!parsed.success) {
    const msg = parsed.error.errors[0]?.message ?? "Invalid input";
    return { error: msg };
  }
  const input = parsed.data;

  // 2. Rate limit by IP
  const headersList = await headers();
  const ip =
    headersList.get("x-forwarded-for")?.split(",")[0]?.trim() ??
    headersList.get("x-real-ip") ??
    "anonymous";
  const allowed = await isCheckoutAllowed(ip);
  if (!allowed) {
    return { error: "Too many checkout attempts. Please wait a few minutes and try again." };
  }

  // 3. Load current cart
  const cart = await getCart();
  if (!cart || cart.items.length === 0) {
    return { error: "Your cart is empty." };
  }

  const admin = supabaseAdmin();

  // 4. Re-fetch prices from DB (never trust cart-cached prices)
  const productIds = cart.items.map((i) => i.product_id).filter(Boolean);
  const { data: freshProducts, error: productError } = await admin
    .from("public_products")
    .select(
      "id, title, slug, sku, price, compare_at_price, quantity, condition, brand, model, storage, color, battery_health, warranty_days, allow_pickup, allow_shipping, translations",
    )
    .in("id", productIds);

  if (productError || !freshProducts) {
    console.error("[checkout] Product fetch error:", productError?.message);
    return { error: "Could not verify product prices. Please try again." };
  }

  type FreshProduct = (typeof freshProducts)[number];
  const productMap = new Map<string, FreshProduct>(
    freshProducts
      .filter((p): p is FreshProduct & { id: string } => p.id !== null)
      .map((p) => [p.id as string, p]),
  );

  // 5. Validate inventory and fulfillment method
  for (const item of cart.items) {
    const product = productMap.get(item.product_id);

    if (!product) {
      return { error: "One or more items are no longer available." };
    }

    const stock = product.quantity ?? 0;
    if (stock < item.quantity) {
      const title = product.title ?? "An item";
      return {
        error:
          stock === 0
            ? `"${title}" is out of stock.`
            : `"${title}" only has ${stock} unit(s) available.`,
      };
    }

    if (input.fulfillmentMethod === "pickup" && !product.allow_pickup) {
      return { error: `"${product.title ?? "An item"}" is not available for pickup.` };
    }
    if (input.fulfillmentMethod === "shipping" && !product.allow_shipping) {
      return { error: `"${product.title ?? "An item"}" is not available for shipping.` };
    }
  }

  // 6. Settings + coupon
  const settings = await getStoreSettings();

  let discountTotal = 0;
  let couponId: string | null = null;
  let appliedCouponCode: string | null = null;

  const subtotal = computeSubtotal(cart.items, productMap);

  if (input.couponCode) {
    const couponResult = await applyCoupon(admin, input.couponCode, subtotal);
    if (couponResult.error) return { error: couponResult.error };
    discountTotal = couponResult.discountAmount ?? 0;
    couponId = couponResult.couponId ?? null;
    appliedCouponCode = input.couponCode.toUpperCase();
  }

  // 7. Calculate order totals (all in cents)
  const shippingTotal = 0; // Calculated by Stripe Tax
  const total = Math.max(0, subtotal - discountTotal + shippingTotal);

  // 8. Get authenticated user (if any)
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  // 9. Generate sequential order number
  let orderNumber: string;
  try {
    const { data: numData } = await admin.rpc(
      "get_next_order_number" as never,
      {} as never,
    );
    orderNumber = (numData as unknown as string) ?? `WC-${Date.now()}`;
  } catch {
    orderNumber = `WC-${Date.now()}`;
  }

  // 10. Create pending order
  const { data: order, error: orderError } = await admin
    .from("orders")
    .insert({
      order_number: orderNumber,
      user_id: user?.id ?? null,
      customer_email: input.customerEmail,
      customer_name: input.customerName,
      customer_phone: input.customerPhone ?? null,
      customer_locale: input.customerLocale ?? "en",
      fulfillment_method: input.fulfillmentMethod as FulfillmentMethod,
      status: "pending",
      payment_status: "unpaid",
      subtotal,
      discount_total: discountTotal,
      shipping_total: shippingTotal,
      tax_total: 0,
      total,
      currency: "usd",
      coupon_id: couponId,
      coupon_code: appliedCouponCode,
    })
    .select("id, guest_access_token")
    .single();

  if (orderError || !order) {
    console.error("[checkout] Order insert error:", orderError?.message);
    return { error: "Could not create order. Please try again." };
  }

  // 11. Create order_items snapshots
  const now = new Date();
  const orderItemsPayload = cart.items.map((item) => {
    const product = productMap.get(item.product_id)!;
    const unitPrice = product.price ?? 0;
    const lineTotal = unitPrice * item.quantity;
    const warrantyDays = product.warranty_days ?? 30;
    const warrantyExpiresAt = new Date(
      now.getTime() + warrantyDays * 24 * 60 * 60 * 1000,
    ).toISOString();

    return {
      order_id: order.id,
      product_id: item.product_id,
      product_title: product.title ?? "Unknown Product",
      product_slug: product.slug ?? null,
      product_sku: product.sku ?? null,
      unit_price: unitPrice,
      quantity: item.quantity,
      line_total: lineTotal,
      device_brand: product.brand ?? null,
      device_model: product.model ?? null,
      device_storage: product.storage ?? null,
      device_color: product.color ?? null,
      device_condition: product.condition ?? null,
      battery_health: product.battery_health ?? null,
      warranty_days: warrantyDays,
      warranty_expires_at: warrantyExpiresAt,
    };
  });

  const { error: itemsError } = await admin
    .from("order_items")
    .insert(orderItemsPayload);

  if (itemsError) {
    console.error("[checkout] Order items insert error:", itemsError.message);
    await admin.from("orders").delete().eq("id", order.id);
    return { error: "Could not save order items. Please try again." };
  }

  // 12. Build Stripe line items (amounts are already in cents)
  const lineItems: Stripe.Checkout.SessionCreateParams.LineItem[] = cart.items.map(
    (item) => {
      const product = productMap.get(item.product_id)!;
      return {
        price_data: {
          currency: "usd",
          unit_amount: Math.round(product.price ?? 0),
          product_data: {
            name: product.title ?? "Product",
          },
        },
        quantity: item.quantity,
      };
    },
  );

  // 13. Add shipping insurance if subtotal exceeds threshold
  if (
    input.fulfillmentMethod === "shipping" &&
    subtotal >= settings.shipping_insurance_threshold &&
    settings.shipping_insurance_amount > 0
  ) {
    lineItems.push({
      price_data: {
        currency: "usd",
        unit_amount: settings.shipping_insurance_amount,
        product_data: { name: "Shipping Insurance" },
      },
      quantity: 1,
    });
  }

  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "";
  const locale = input.customerLocale ?? "en";
  const guestToken = order.guest_access_token as string;
  const taxEnabled = isStripeTaxEnabled(settings);

  // 14. Create Stripe Checkout Session
  const sessionParams: Stripe.Checkout.SessionCreateParams = {
    mode: "payment",
    payment_method_types: ["card"],
    line_items: lineItems,
    customer_email: input.customerEmail,
    metadata: {
      order_id: order.id,
      order_number: orderNumber,
      fulfillment_method: input.fulfillmentMethod,
      cart_id: cart.id,
    },
    success_url: `${siteUrl}/${locale}/order-confirmation?token=${guestToken}`,
    cancel_url: `${siteUrl}/${locale}/checkout`,
    ...(input.fulfillmentMethod === "shipping"
      ? { shipping_address_collection: { allowed_countries: ["US"] } }
      : {}),
    ...(taxEnabled ? { automatic_tax: { enabled: true } } : {}),
  };

  let stripeSession: Stripe.Checkout.Session;
  try {
    stripeSession = await stripe.checkout.sessions.create(sessionParams);
  } catch (stripeErr) {
    console.error("[checkout] Stripe session create error:", stripeErr);
    await admin.from("orders").delete().eq("id", order.id);
    return { error: "Could not start checkout. Please try again." };
  }

  // 15. Save stripe_checkout_session_id to order
  await admin
    .from("orders")
    .update({ stripe_checkout_session_id: stripeSession.id })
    .eq("id", order.id);

  if (!stripeSession.url) {
    return { error: "Checkout session URL missing. Please try again." };
  }

  return { url: stripeSession.url };
}

// ─── Cart validation helper ───────────────────────────────────────────────────

export interface CheckoutCartValidation {
  valid: boolean;
  unavailableItems: string[];
}

export async function validateCheckoutCart(): Promise<CheckoutCartValidation> {
  const cart = await getCart();
  if (!cart || cart.items.length === 0) {
    return { valid: false, unavailableItems: [] };
  }

  const admin = supabaseAdmin();
  const productIds = cart.items.map((i) => i.product_id);
  const { data: products } = await admin
    .from("public_products")
    .select("id, title, quantity")
    .in("id", productIds);

  const productMap = new Map(
    (products ?? [])
      .filter((p): p is typeof p & { id: string } => p.id !== null)
      .map((p) => [p.id, p]),
  );

  const unavailableItems: string[] = [];
  for (const item of cart.items) {
    const product = productMap.get(item.product_id);
    if (!product || (product.quantity ?? 0) < item.quantity) {
      unavailableItems.push(item.product.title ?? item.product_id);
    }
  }

  return { valid: unavailableItems.length === 0, unavailableItems };
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

type AdminClient = ReturnType<typeof supabaseAdmin>;

function computeSubtotal(
  items: CartItemWithProduct[],
  productMap: Map<string, { price: number | null }>,
): number {
  return items.reduce((sum, item) => {
    const product = productMap.get(item.product_id);
    return sum + (product?.price ?? 0) * item.quantity;
  }, 0);
}

interface CouponResult {
  error?: string;
  discountAmount?: number;
  couponId?: string;
}

async function applyCoupon(
  admin: AdminClient,
  code: string,
  subtotalCents: number,
): Promise<CouponResult> {
  const now = new Date().toISOString();

  const { data: couponRow } = await admin
    .from("coupons")
    .select(
      "id, type, value, minimum_order_amount, usage_limit, used_count, active, starts_at, expires_at",
    )
    .eq("code", code.toUpperCase())
    .eq("active", true)
    .or(`starts_at.is.null,starts_at.lte.${now}`)
    .or(`expires_at.is.null,expires_at.gte.${now}`)
    .maybeSingle();

  if (!couponRow) {
    return { error: "Invalid or expired coupon code." };
  }

  if (
    couponRow.usage_limit !== null &&
    couponRow.used_count >= couponRow.usage_limit
  ) {
    return { error: "This coupon has reached its usage limit." };
  }

  const minOrder = couponRow.minimum_order_amount ?? 0;
  if (subtotalCents < Number(minOrder)) {
    return {
      error: `This coupon requires a minimum order of ${(Number(minOrder) / 100).toFixed(2)}.`,
    };
  }

  // Increment used_count (not perfectly atomic but sufficient for MVP)
  await admin
    .from("coupons")
    .update({ used_count: (couponRow.used_count ?? 0) + 1 })
    .eq("id", couponRow.id);

  let discountAmount = 0;
  const value = Number(couponRow.value);
  if (couponRow.type === "percentage") {
    discountAmount = Math.round(subtotalCents * (value / 100));
  } else if (couponRow.type === "fixed_amount") {
    discountAmount = Math.min(subtotalCents, Math.round(value));
  }
  // free_shipping: discountAmount stays 0 (shipping is $0 in pending order)

  return { discountAmount, couponId: couponRow.id };
}
